CREATE TABLE USUARIO (
    IdUsuario   INTEGER PRIMARY KEY AUTOINCREMENT ID,
    Nombre      TEXT NOT NULL,
    Estado      INTEGER DEFAULT 1,
    FechaIng    DATETIME DEFAULT CURRENT_TIMESTAMP,
    FechaMod    DATETIME DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM USUARIO;
DROP TABLE USUARIO;

INSERT INTO USUARIO (Nombre) VALUES ("fer")
INSERT INTO USUARIO (Nombre) VALUES ("fernando.nagua@epn.edu.ec")